# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-lint
      - id: php-unit
      - id: php-cs
        files: \.(php)$
        args: [--standard=PSR12 -p -s]
      - id: php-cbf
        files: \.(php)$
        args: [--standard=PSR12 -p -s]
      - id: php-cs-fixer
        files: \.(php)$
